/** TMDB poster paths (w500 base applied in seed). */
export const MOVIES_RAW = [
  ['Inception', ['Sci-Fi', 'Thriller'], 2010, 'Dream thieves plant an idea in a CEO mind—layers of reality bend in this heist epic.', '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg'],
  ['The Dark Knight', ['Action', 'Crime'], 2008, 'Batman faces the Joker in a battle for Gotham soul.', '/qJ2tW6WMUDux911r6m7haRef0WH.jpg'],
  ['Interstellar', ['Sci-Fi', 'Drama'], 2014, 'Explorers cross a wormhole to find humanity a new home among the stars.', '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'],
  ['Parasite', ['Thriller', 'Drama'], 2019, 'Two families collide in a razor-sharp class satire.', '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg'],
  ['Spirited Away', ['Animation', 'Fantasy'], 2001, 'A girl enters a bathhouse for spirits in a breathtaking fairy tale.', '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg'],
  ['The Grand Budapest Hotel', ['Comedy', 'Drama'], 2014, 'A lobby boy and a concierge get tangled in a caper across a fictional Europe.', '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg'],
  ['Mad Max: Fury Road', ['Action', 'Sci-Fi'], 2015, 'A desert chase for survival—pure gasoline and fury.', '/hA2ple9q4qnwxp3hKVNhPGipsin.jpg'],
  ['La La Land', ['Romance', 'Musical'], 2016, 'An actress and a pianist chase dreams in Los Angeles.', '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg'],
  ['Get Out', ['Horror', 'Thriller'], 2017, 'A weekend with the in-laws turns sinister in this modern horror classic.', '/tFXcEccSQMf3lfhfXKSU7i5Ujpt.jpg'],
  ['Dune', ['Sci-Fi', 'Adventure'], 2021, 'House Atreides arrives on Arrakis amid prophecy and politics.', '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg'],
  ['The Matrix', ['Sci-Fi', 'Action'], 1999, 'Neo learns reality is a simulation—and chooses the red pill.', '/f89U3ADr1oiB1s9GkdPOEpXUkny.jpg'],
  ['Fight Club', ['Drama', 'Thriller'], 1999, 'An insomniac and a soap salesman start an underground fight ring.', '/rSrN8D91OGrECXcFQ13wUFjIWeP.jpg'],
  ['Forrest Gump', ['Drama', 'Romance'], 1994, 'A kind man drifts through decades of American history.', '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg'],
  ['The Shawshank Redemption', ['Drama'], 1994, 'Two inmates forge hope inside a brutal prison.', '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg'],
  ['Pulp Fiction', ['Crime', 'Drama'], 1994, 'Interlocking stories of hitmen, a boxer, and a briefcase.', '/s7EPJTpGFLx4q85B2TvUgBi2kzh.jpg'],
  ['The Godfather', ['Crime', 'Drama'], 1972, 'The Corleone family rises in postwar America.', '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg'],
  ['Whiplash', ['Drama', 'Music'], 2014, 'A drummer pushes past breaking point under a ruthless instructor.', '/lIv1QexAJfnkpsCwfglCBtmnibL.jpg'],
  ['Blade Runner 2049', ['Sci-Fi', 'Thriller'], 2017, 'A replicant hunter uncovers a secret that could reshape society.', '/gajva2L0rPYkEWj3FlsxCsQs0nP.jpg'],
  ['Arrival', ['Sci-Fi', 'Drama'], 2016, 'Linguists race to understand aliens before panic spreads.', '/x2FJsf1ElAgr63Y3nPt5HWzSYmX.jpg'],
  ['Her', ['Romance', 'Sci-Fi'], 2013, 'A man falls for an AI voice assistant in near-future LA.', '/bV5rEUhyT6xRmd13PRDfgLeghKj.jpg'],
  ['Ex Machina', ['Sci-Fi', 'Thriller'], 2015, 'A coder tests a humanoid AI in an isolated estate.', '/9gfbl7xdOG4NjN8FnpjtxNHTUh5.jpg'],
  ['The Social Network', ['Drama'], 2010, 'The founding of Facebook fractures friendships and futures.', '/n0yjwtM3XDdMcw8jeK8HKEFPKCD.jpg'],
  ['No Country for Old Men', ['Thriller', 'Crime'], 2007, 'A hunter finds drug money and a relentless killer follows.', '/n1NN5aBeFlb1sGMMbf5SfnDKvW5.jpg'],
  ['There Will Be Blood', ['Drama'], 2007, 'An oilman ruthless ambition consumes everything around him.', '/faSB8fRzooEEAAhbGqiZvO1EmTg.jpg'],
  ['The Prestige', ['Drama', 'Thriller'], 2006, 'Rival magicians duel with ever more dangerous illusions.', '/tRNlZbgNCNOpWdZWzANFHDcxX9.jpg'],
  ['The Departed', ['Crime', 'Thriller'], 2006, 'Moles inside the police and the mob tighten the noose.', '/nT97ifVT2J1yMQ0NPWFXrHuSOmm.jpg'],
  ['Gladiator', ['Action', 'Drama'], 2000, 'A general seeks vengeance in the Roman arena.', '/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg'],
  ['Saving Private Ryan', ['War', 'Drama'], 1998, 'Soldiers cross Normandy to bring one man home.', '/uqx37cS8cpHg8UxlzJ1w1L0vRxX.jpg'],
  ['The Lord of the Rings: The Fellowship of the Ring', ['Fantasy', 'Adventure'], 2001, 'A hobbit carries a ring toward Mount Doom.', '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'],
  ['The Lord of the Rings: The Two Towers', ['Fantasy', 'Adventure'], 2002, 'Middle-earth braces for war as Frodo journeys onward.', '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg'],
  ['The Lord of the Rings: The Return of the King', ['Fantasy', 'Adventure'], 2003, 'The final battle for Middle-earth begins.', '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg'],
  ['Spider-Man: Into the Spider-Verse', ['Animation', 'Action'], 2018, 'Teenagers from parallel worlds team up as Spider-People.', '/iiZZdoQBEYBv6id8su7AcL9Owmr.jpg'],
  ['Everything Everywhere All at Once', ['Sci-Fi', 'Comedy'], 2022, 'A laundromat owner jumps across multiverses to save her family.', '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg'],
  ['Top Gun: Maverick', ['Action', 'Drama'], 2022, 'Pete Maverick Mitchell trains a new generation of pilots.', '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg'],
  ['Oppenheimer', ['Drama', 'Thriller'], 2023, 'The race to build the atomic bomb and its moral weight.', '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'],
  ['Barbie', ['Comedy', 'Fantasy'], 2023, 'Barbie questions her perfect world and steps into the real one.', '/iuFNMS8UOtcbVz2FGzGtWQhFfA6.jpg'],
  ['John Wick', ['Action', 'Thriller'], 2014, 'A retired hitman returns for revenge—and a dog.', '/fZPSdJyP0ONGLBFPk456Uj5H7hm.jpg'],
  ['Coco', ['Animation', 'Family'], 2017, 'A boy visits the Land of the Dead to uncover family history.', '/gGEsBPAijhVUFoiNpgZXRvRVcbA.jpg'],
  ['Soul', ['Animation', 'Drama'], 2020, 'A jazz musician soul takes a detour before the great gig.', '/hm58Jw4LwQlMlLaR0i2VfOZqJJU.jpg'],
  ['Knives Out', ['Comedy', 'Mystery'], 2019, 'A detective peels back a wealthy family secrets after a death.', '/pThyQovXQrw2sx0knO3WDxVPyXQ.jpg'],
  ['The Batman', ['Action', 'Crime'], 2022, 'A younger Batman hunts the Riddler through Gotham corruption.', '/74xTEgt7R3pXoqb9yhRc0cX4YEr.jpg'],
  ['Avatar', ['Sci-Fi', 'Adventure'], 2009, 'A marine goes native on the moon Pandora.', '/jRXYjXNq0Cs2TcEqLmuXcpW8MXT.jpg'],
  ['Avatar: The Way of Water', ['Sci-Fi', 'Adventure'], 2022, 'The Sully family defends their home across land and sea.', '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg'],
  ['Black Panther', ['Action', 'Sci-Fi'], 2018, 'TChalla returns to Wakanda to claim the throne.', '/uxzzxjijcfP7wCIF0C9Zz9YSImS.jpg'],
  ['Avengers: Endgame', ['Action', 'Sci-Fi'], 2019, 'The Avengers assemble one last time against Thanos.', '/or06FN3Dka5tukK1e9sl16pB3iy.jpg'],
  ['Toy Story', ['Animation', 'Comedy'], 1995, 'Cowboy and space ranger toys compete for a boy affection.', '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg'],
  ['Finding Nemo', ['Animation', 'Adventure'], 2003, 'A clownfish crosses the ocean to find his son.', '/eHuGQ10FUzK1nY4QGzBBUxJkPBL.jpg'],
  ['The Lion King', ['Animation', 'Drama'], 1994, 'A young lion prince flees guilt—and returns to reclaim pride rock.', '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg'],
  ['Jurassic Park', ['Sci-Fi', 'Adventure'], 1993, 'Dinosaurs walk again—and chaos follows.', '/oU7Oq2kFAAlGqbU4TvAEsZh4ebp.jpg'],
  ['Back to the Future', ['Sci-Fi', 'Comedy'], 1985, 'A teen accidentally time-travels to 1955 in a DeLorean.', '/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg'],
  ['Terminator 2: Judgment Day', ['Sci-Fi', 'Action'], 1991, 'A reprogrammed Terminator protects a future leader.', '/5M0j0B7ab1PELEuYuBdMBxvLmDX.jpg'],
  ['Alien', ['Horror', 'Sci-Fi'], 1979, 'The crew of the Nostromo meets the perfect organism.', '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg'],
  ['Aliens', ['Action', 'Sci-Fi'], 1986, 'Ripley returns with marines to a colony overrun by xenomorphs.', '/r1x5JG3qtsGA4BA6gTru8kuhYgv.jpg'],
  ['The Thing', ['Horror', 'Sci-Fi'], 1982, 'Antarctic researchers distrust who is still human.', '/tzGY49kseSE9QAKk877uuCBuAGN.jpg'],
  ['Heat', ['Crime', 'Drama'], 1995, 'A master thief and a relentless detective circle each other in LA.', '/rr7U0qpG0WGkwX81KiLY6zykjvw.jpg'],
  ['Se7en', ['Crime', 'Thriller'], 1995, 'Two detectives hunt a killer themed on the seven deadly sins.', '/6yoghtyTpznpBik8EngEmJskVU.jpg'],
  ['The Silence of the Lambs', ['Thriller', 'Horror'], 1991, 'A trainee FBI agent consults a cannibal psychiatrist to catch a killer.', '/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg'],
  ['Goodfellas', ['Crime', 'Drama'], 1990, 'A mob associate rises and falls across decades.', '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg'],
  ['Casino', ['Crime', 'Drama'], 1995, 'Las Vegas power plays between mob, money, and marriage.', '/4TS0OJP2Ll9GQnpouL5u6AmB6WK.jpg'],
  ['The Wolf of Wall Street', ['Comedy', 'Crime'], 2013, 'Excess and fraud fuel a stockbroker meteoric rise.', '/34m2tygAYBGqA9MXKhRDtzYc4DB.jpg'],
  ['Inglourious Basterds', ['War', 'Drama'], 2009, 'A band of Jewish soldiers plots against the Nazis in occupied France.', '/7sfbEnaARXDDxKm4jdWThCt8vdz.jpg'],
  ['Django Unchained', ['Western', 'Drama'], 2012, 'A freed slave and a bounty hunter hunt the South deadliest men.', '/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg'],
  ['Kill Bill: Vol. 1', ['Action', 'Thriller'], 2003, 'The Bride wakes from a coma and starts her revenge list.', '/v7TaX6kLQlgup7RgvKcC7QqOW9.jpg'],
  ['The Truman Show', ['Drama', 'Sci-Fi'], 1998, 'A man discovers his entire life is a TV show.', '/lnpibZP2PuoXGd5lA7jxjseMlX9.jpg'],
  ['Eternal Sunshine of the Spotless Mind', ['Romance', 'Sci-Fi'], 2004, 'A couple erases memories of each other—and regrets it.', '/5MwkWH9tYHv3mV9OdYTMR5qreMw.jpg'],
  ['The Big Lebowski', ['Comedy', 'Crime'], 1998, 'The Dude abides through mistaken identity and bowling.', '/aKocehxngLwTFW5HeRmT581253.jpg'],
  ['Shaun of the Dead', ['Comedy', 'Horror'], 2004, 'Slacker friends stumble through a zombie apocalypse.', '/dgXPhzNJH8H8HCfxUbsb5AoBbqy.jpg'],
  ['Scott Pilgrim vs. the World', ['Action', 'Comedy'], 2010, 'A bassist battles seven evil exes for the girl.', '/g5IoOSYeFdA0DZC7rUCkP9r0Byf.jpg'],
  ['Baby Driver', ['Action', 'Crime'], 2017, 'A getaway driver wants out after one last job.', '/rmnQ9jKWw2AzKfJIFQDj0uovxZ8.jpg'],
  ['Drive', ['Crime', 'Drama'], 2011, 'A stunt driver moonlights as a heist wheelman—and pays the price.', '/602vevIURmpDfzbnv5Ubi6wIkQm.jpg'],
  ['Nightcrawler', ['Crime', 'Thriller'], 2014, 'A freelance cameraman chases grisly news footage in LA.', '/jOjdW1fUVpD3QNfgH0cPQCVl2Z5.jpg'],
  ['Gone Girl', ['Thriller', 'Drama'], 2014, 'A husband becomes the prime suspect when his wife vanishes.', '/gdiLtOf4bSDPqTany2VlNet6Xps.jpg'],
  ['Prisoners', ['Thriller', 'Crime'], 2013, 'A father takes matters into his own hands when his daughter disappears.', '/wAoi6UqDqmS7dS4R6Tyx0uglav0.jpg'],
  ['The Revenant', ['Adventure', 'Drama'], 2015, 'A fur trapper survives the wilderness to avenge his son.', '/oXUQEPhrNhmXwAHF4khLG1ljpv9.jpg'],
  ['Madagascar', ['Animation', 'Comedy'], 2005, 'Zoo animals wash ashore on a wild island.', '/2a9qDKbVygEsnzZnU5QwnK5yKv2.jpg'],
  ['Shrek', ['Animation', 'Comedy'], 2001, 'An ogre rescues a princess to get his swamp back.', '/iB64vpL3dUpKGC7QHhUeL2UDWzy.jpg'],
  ['Ratatouille', ['Animation', 'Comedy'], 2007, 'A rat with culinary genius cooks under a chef hat.', '/npHNjWdSCPVnL1TUqAu2uTyPs5f.jpg'],
  ['WALL·E', ['Animation', 'Sci-Fi'], 2008, 'A lonely robot cleans Earth—and finds love among the stars.', '/hbhFnRzzg6ZDjm8rlD4xMYeDvFc.jpg'],
  ['Up', ['Animation', 'Adventure'], 2009, 'A widower flies his house to South America with a stowaway scout.', '/eAdjuVeZjP8D5GAdTfb63q43Y07.jpg'],
  ['Inside Out', ['Animation', 'Comedy'], 2015, 'Riley emotions argue inside her head after a big move.', '/lRHE0vzfXoQH0gCdNBWMmDfhfmz.jpg'],
  ['Moana', ['Animation', 'Adventure'], 2016, 'A Polynesian voyager restores the heart of Te Fiti.', '/4J1Vu6nF3Eljry3r94E0D2oLtGY.jpg'],
  ['Encanto', ['Animation', 'Musical'], 2021, 'A Colombian family magic falters—except for one granddaughter.', '/4j0PHH3W6OFGsQ37mjpwuq0bpr.jpg'],
  ['Raya and the Last Dragon', ['Animation', 'Fantasy'], 2021, 'A warrior seeks a dragon to reunite a fractured land.', '/lPsD10PP4jUGqXVbfDWk0aCQWEq.jpg'],
  ['Zootopia', ['Animation', 'Comedy'], 2016, 'A bunny cop and a fox con artist crack a city-wide mystery.', '/hlK0f0rAQrx3x0B4ETLmJq9f3R7.jpg'],
  ['Frozen', ['Animation', 'Musical'], 2013, 'Sisterhood and ice powers reshape a Nordic kingdom.', '/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg'],
  ['Titanic', ['Romance', 'Drama'], 1997, 'A ship of dreams becomes a tragedy—and a love story survives.', '/9xjZS2rlVxm8SFx8kPC3aIGCOYd.jpg'],
  ['The Notebook', ['Romance', 'Drama'], 2004, 'A couple decades-long love read from a notebook in the present.', '/rNzQyW4f8B8cQeg7TyHbNoDrLtT.jpg'],
  ['Pride & Prejudice', ['Romance', 'Drama'], 2005, 'Elizabeth Bennet and Mr. Darcy spar and soften.', '/f9uIuyQwLDsZja88u8iTVgTMN5s.jpg'],
  ['Amélie', ['Romance', 'Comedy'], 2001, 'A Paris waitress quietly brightens strangers lives.', '/wOtP29lMvYdjhXEU4bq4c0kqhkV.jpg'],
  ['The Intouchables', ['Comedy', 'Drama'], 2011, 'An unlikely friendship between a quadriplegic man and his caregiver.', '/bffsngy18qlSkI4ETKWler_L4rM.jpg'],
  ['The Menu', ['Horror', 'Comedy'], 2022, 'A couple travels to an exclusive island restaurant where the chef has dark plans.', '/fPtLScBYl0c0g2GGUSFo5e4P29T.jpg'],
];
